# Generated by Django 6.0 on 2025-12-12 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField()),
                ('suitability_score', models.PositiveIntegerField(help_text='0–100 overall suitability score')),
                ('nutrient_score', models.PositiveIntegerField(blank=True, null=True)),
                ('water_retention_score', models.PositiveIntegerField(blank=True, null=True)),
                ('drainage_score', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(default='System Admin', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('cell', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooperatives', to='tracker.adminprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('village', models.CharField(max_length=100)),
                ('main_crop', models.CharField(blank=True, max_length=100)),
                ('farm_size_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending fees'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers', to='tracker.cooperative')),
            ],
        ),
        migrations.CreateModel(
            name='FieldPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('location_description', models.CharField(blank=True, max_length=255)),
                ('size_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('main_crop', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('harvest', 'Ready for harvest'), ('rest', 'Resting')], default='active', max_length=20)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='tracker.cooperative')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='tracker.farmer')),
            ],
            options={
                'db_table': 'fields',
            },
        ),
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('suitability_score', models.PositiveIntegerField(blank=True, help_text='0–100', null=True)),
                ('description', models.TextField(blank=True)),
                ('expected_yield', models.CharField(blank=True, max_length=100)),
                ('season', models.CharField(blank=True, max_length=50)),
                ('is_top_choice', models.BooleanField(default=False)),
                ('ai_insight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='tracker.aiinsight')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_recommendations', to='tracker.fieldplot')),
            ],
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='tracker.fieldplot'),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=50, unique=True)),
                ('sensor_type', models.CharField(choices=[('moisture', 'Soil moisture'), ('temperature', 'Soil temperature'), ('ph', 'pH sensor'), ('npk', 'NPK sensor'), ('weather', 'Weather node')], max_length=20)),
                ('location_on_field', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('battery_level', models.PositiveIntegerField(default=100)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='tracker.fieldplot')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('moisture', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('nitrogen', models.FloatField(blank=True, null=True)),
                ('phosphorus', models.FloatField(blank=True, null=True)),
                ('potassium', models.FloatField(blank=True, null=True)),
                ('conductivity', models.FloatField(blank=True, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='tracker.sensor')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
