# Generated by Django 6.0 on 2025-12-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinsight',
            name='suitability_score',
            field=models.PositiveIntegerField(help_text='0–100 overall score'),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='suitability_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
